services:
  sync:
    image: yellowstar210/sync1:latest
    ports:
      - "8080:80"
    environment:
      - PRIVATE_KEY=${PRIVATE_KEY}

  ollama:
    image: ollama/ollama:0.3.12
    ports:
      - "11439:11434"
    volumes:
      - ollama:/root/.ollama
    restart: unless-stopped

  sixgpt3:
    image: sixgpt/miner:latest
    ports:
      - "3000:3000"
    depends_on:
      - ollama
    environment:
      - VANA_PRIVATE_KEY=${PRIVATE_KEY}
      - VANA_NETWORK=${VANA_NETWORK}
      - OLLAMA_API_URL=http://ollama:11434/api
    restart: no

volumes:
  ollama:
